import {
  Mail,
  Phone,
  MapPin,
  Github,
  Linkedin,
  Twitter,
  ExternalLink,
  Calendar,
  Clock,
  User,
  Building,
  DollarSign,
  MessageSquare,
  Send,
  CheckCircle,
  AlertCircle,
  Info,
  X,
  Menu,
  Sun,
  Moon,
  Star,
  Award,
  Code,
  Database,
  Server,
  Globe,
  Smartphone,
  Tablet,
  Monitor,
  Zap,
  Shield,
  Lock,
  Key,
  Search,
  Filter,
  Download,
  Upload,
  Edit,
  Trash2,
  Plus,
  Minus,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Home,
  Settings,
  HelpCircle,
  FileText,
  ImageIcon as Image,
  Video,
  Music,
  Folder,
  File,
  Save,
  Copy,
  Share,
  Heart,
  ThumbsUp,
  Eye,
  EyeOff,
  Bell,
  BellOff,
  Bookmark,
  Tag,
  Flag,
  RefreshCwIcon as Refresh,
  RotateCcw,
  Maximize,
  Minimize,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
} from "lucide-react"

export const Icons = {
  // Contact & Communication
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  messageSquare: MessageSquare,
  send: Send,

  // Social Media
  github: Github,
  linkedin: Linkedin,
  twitter: Twitter,

  // Navigation & UI
  externalLink: ExternalLink,
  menu: Menu,
  x: X,
  home: Home,
  settings: Settings,
  helpCircle: HelpCircle,

  // Calendar & Time
  calendar: Calendar,
  clock: Clock,

  // User & Business
  user: User,
  building: Building,
  dollarSign: DollarSign,

  // Status & Feedback
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  info: Info,

  // Theme
  sun: Sun,
  moon: Moon,

  // Skills & Achievements
  star: Star,
  award: Award,
  code: Code,
  database: Database,
  server: Server,
  globe: Globe,

  // Devices
  smartphone: Smartphone,
  tablet: Tablet,
  monitor: Monitor,

  // Features
  zap: Zap,
  shield: Shield,
  lock: Lock,
  key: Key,

  // Actions
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,
  edit: Edit,
  trash2: Trash2,
  plus: Plus,
  minus: Minus,
  save: Save,
  copy: Copy,
  share: Share,

  // Arrows & Navigation
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,

  // Files & Media
  fileText: FileText,
  image: Image,
  video: Video,
  music: Music,
  folder: Folder,
  file: File,

  // Interactions
  heart: Heart,
  thumbsUp: ThumbsUp,
  eye: Eye,
  eyeOff: EyeOff,
  bell: Bell,
  bellOff: BellOff,
  bookmark: Bookmark,
  tag: Tag,
  flag: Flag,

  // Controls
  refresh: Refresh,
  rotateCcw: RotateCcw,
  maximize: Maximize,
  minimize: Minimize,
  volume2: Volume2,
  volumeX: VolumeX,
  play: Play,
  pause: Pause,
  square: Square,
  skipBack: SkipBack,
  skipForward: SkipForward,
  fastForward: FastForward,
  rewind: Rewind,
}

export type IconName = keyof typeof Icons
